#!/bin/bash

adduser --disabled-password --gecos "" $SFTP_USER

echo "$SFTP_USER:$SFTP_PASSWORD" | chpasswd

echo "$AWS_ACCESS_KEY_ID:$AWS_SECRET_ACCESS_KEY" > /s3credentials
chmod 600 /s3credentials

mkdir -p /mnt/s3
s3fs $S3_BUCKET /mnt/s3 -o passwd_file=/s3credentials -o allow_other -o uid=$(id -u $SFTP_USER)

ln -s /mnt/s3 /home/$SFTP_USER

#EXCLUDE
echo "SFTP_PASSWORD: $SFTP_PASSWORD"
echo "AWS_ACCESS_KEY_ID: $AWS_ACCESS_KEY_ID"
#EXCLUDE

echo "SFTP user: $SFTP_USER"
echo "S3 Bucket: $S3_BUCKET"
echo "Ready to accept connections..."
exec /usr/sbin/sshd -D
